# Generated by Django 4.1.1 on 2022-11-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='pigeon_doveID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
