# Generated by Django 4.1.1 on 2022-11-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0003_user_rename_pigeon_doveid_pigeon_rfid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeon',
            name='id',
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='doveID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
