# Generated by Django 4.1.1 on 2022-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0004_remove_pigeon_id_alter_pigeon_doveid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='doveID',
            field=models.CharField(max_length=100),
        ),
    ]
