# Generated by Django 4.1.1 on 2022-11-17 03:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dataAnalysisManagement', '0012_alter_pigeon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pigeonPhotos', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
