# Generated by Django 4.1.1 on 2022-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0013_alter_pigeon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
