# Generated by Django 3.1.8 on 2022-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0014_alter_pigeon_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pigeon',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
