# Generated by Django 3.1.8 on 2022-11-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0015_auto_20221117_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRecord_filters_summary',
            fields=[
                ('trainRecordId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('startIndex', models.CharField(max_length=100)),
                ('endIndex', models.CharField(max_length=100, null=True)),
                ('updateTime', models.CharField(max_length=100)),
                ('realDistance', models.CharField(max_length=100)),
                ('realSpeed', models.CharField(max_length=100)),
                ('straightDistance', models.CharField(max_length=100)),
                ('straightSpeed', models.CharField(max_length=100)),
                ('routeEfficiency', models.CharField(max_length=100)),
                ('settingTime', models.CharField(max_length=100)),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
