# Generated by Django 4.1.3 on 2022-12-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisManagement', '0016_trainrecord_filters_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=100)),
                ('releaseDate', models.CharField(max_length=100)),
                ('releaseTime', models.CharField(max_length=100)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='LocusText',
            fields=[
                ('locusID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UTC', models.DateTimeField(null=True)),
                ('fix', models.CharField(max_length=100, null=True)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
                ('highlight', models.BooleanField(default=False, null=True)),
                ('realDistance', models.FloatField(null=True)),
                ('gpsHeight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('gpsSpeed', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('direction', models.IntegerField(null=True)),
                ('satNum', models.IntegerField(null=True)),
                ('HDOP', models.IntegerField(null=True)),
                ('upload', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ringID', models.CharField(max_length=100, null=True)),
                ('lazerID', models.CharField(max_length=100, null=True)),
                ('fixedID', models.CharField(max_length=100, null=True)),
                ('firmwareVer', models.CharField(max_length=100, null=True)),
                ('fake99', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainRecord',
            fields=[
                ('trainRecordId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recordName', models.CharField(max_length=100, null=True)),
                ('settingTime', models.DateTimeField(null=True)),
                ('periodicMode', models.CharField(max_length=100, null=True)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('straightDistance', models.FloatField(null=True)),
                ('straightSpeed', models.FloatField(null=True)),
                ('realDistance', models.FloatField(null=True)),
                ('realSpeed', models.FloatField(null=True)),
                ('startPosition', models.CharField(max_length=100, null=True)),
                ('startLatitude', models.FloatField(null=True)),
                ('startLongitude', models.FloatField(null=True)),
                ('goalLatitude', models.FloatField(null=True)),
                ('goalLongitude', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
                ('settingTimeUpload', models.BooleanField(default=False, null=True)),
                ('completeUpload', models.BooleanField(default=False, null=True)),
                ('updateTime', models.CharField(max_length=100, null=True)),
                ('fixNum', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mxID',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='dataAnalysi_name_9705b1_idx'),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='activityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.activity'),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='mxID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.user'),
        ),
        migrations.AddField(
            model_name='module',
            name='mxID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.user'),
        ),
        migrations.AddField(
            model_name='locustext',
            name='moduleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.module'),
        ),
        migrations.AddField(
            model_name='locustext',
            name='trainRecordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.trainrecord'),
        ),
        migrations.AddField(
            model_name='activity',
            name='mxID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataAnalysisManagement.user'),
        ),
        migrations.AddIndex(
            model_name='trainrecord',
            index=models.Index(fields=['mxID', 'settingTime'], name='dataAnalysi_mxID_id_ad262b_idx'),
        ),
        migrations.AddIndex(
            model_name='locustext',
            index=models.Index(fields=['moduleID'], name='dataAnalysi_moduleI_407f73_idx'),
        ),
    ]
